import {StyleSheet} from 'react-native';

import {normalize} from 'App/Theme/Metrics';
import {Colors} from 'App/Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  cameraView: {
    alignSelf: 'center',
    height: normalize(177),
    width: normalize(240),
    borderRadius: normalize(8),
    // backgroundColor: ,
    overflow: 'hidden',
  },
  preview: {
    flex: 1,
    // justifyContent: 'flex-end',
    // alignItems: 'center',
  },
  capture: {
    flex: 0,
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 15,
    paddingHorizontal: 20,
    alignSelf: 'center',
    margin: 20,
  },
  facesContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    top: 0,
  },
  text: {
    padding: 10,
    borderWidth: 2,
    borderRadius: 2,
    position: 'absolute',
    borderColor: '#F00',
    justifyContent: 'center',
  },
  textBlock: {
    color: '#F00',
    position: 'absolute',
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  cameraNotAuthorized: {
    padding: 20,
    paddingTop: 35,
  },
  cameraLoading: {flex: 1, alignSelf: 'center'},

  cameraTopLeft: {
    position: 'absolute',
    margin: 10,
    backgroundColor: Colors.transparent,
    height: normalize(46),
    width: normalize(50),
    borderColor: Colors.error,
    borderTopLeftRadius: normalize(8),
    borderLeftWidth: normalize(2),
    borderTopWidth: normalize(2),
  },
  cameraTopRight: {
    right: 0,
    top: 0,
    position: 'absolute',
    margin: 10,
    backgroundColor: Colors.transparent,
    height: normalize(46),
    width: normalize(50),
    borderColor: Colors.error,
    borderTopRightRadius: normalize(8),
    borderRightWidth: normalize(2),
    borderTopWidth: normalize(2),
  },
  cameraBottomRight: {
    right: 0,
    bottom: 0,
    position: 'absolute',
    margin: 10,
    backgroundColor: Colors.transparent,
    height: normalize(46),
    width: normalize(50),
    borderColor: Colors.error,
    borderBottomRightRadius: normalize(8),
    borderRightWidth: normalize(2),
    borderBottomWidth: normalize(2),
  },
  cameraBottomLeft: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    margin: 10,
    backgroundColor: Colors.transparent,
    height: normalize(46),
    width: normalize(50),
    borderColor: Colors.error,
    borderBottomLeftRadius: normalize(8),
    borderLeftWidth: normalize(2),
    borderBottomWidth: normalize(2),
  },
});
